"""AI advisor — a daily agent that turns your portfolio into suggestions.

This is the brain of the assistant. It composes the data the rest of the app
already produces (holdings + cost basis, live prices + momentum, the full
unrealized-gain history, realized gains) with recent news, sends it all to
Claude, and gets back concrete buy / hold / trim / sell suggestions for the week
ahead — one set tuned for low risk, one for high risk.

Layers, kept separate like the rest of the app:

  - ``ClaudeClient`` — an I/O boundary onto the Claude Messages API, reached with
    the Python standard library only (``urllib``), matching ``market_data.py``
    and ``news_data.py``. Swap it for another LLM and nothing else changes.
  - ``AIAdvisorService`` — the business logic. Gathers context, builds the
    prompt, asks Claude for structured JSON, caches the result, persists it so
    it survives restarts, and refreshes every two hours during market hours.

Everything degrades gracefully: no ``ANTHROPIC_API_KEY`` -> the advisor reports
it's "not configured" and the UI shows a hint; a failed call -> the last good
suggestions stay on screen and an error note is attached.

Not financial advice — suggestions are generated by a model and can be wrong.
"""

import json
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone

try:  # stdlib on Python 3.9+, used only for US market-hours math
    from zoneinfo import ZoneInfo

    _EASTERN = ZoneInfo("America/New_York")
except Exception:  # pragma: no cover - fallback if tz data is unavailable
    _EASTERN = None


# --- US market hours ----------------------------------------------------

def is_market_open(now_utc: datetime = None) -> bool:
    """True during regular US market hours (Mon-Fri, 9:30-16:00 ET).

    Ignores holidays — good enough to gate a background refresh loop. If tz data
    isn't available, assume open so the advisor still refreshes on schedule.
    """
    now_utc = now_utc or datetime.now(timezone.utc)
    if _EASTERN is None:
        return now_utc.weekday() < 5
    et = now_utc.astimezone(_EASTERN)
    if et.weekday() >= 5:  # Saturday / Sunday
        return False
    minutes = et.hour * 60 + et.minute
    return 9 * 60 + 30 <= minutes <= 16 * 60


# --- Claude client (Messages API over urllib) ---------------------------

# The structured shape we force Claude to return, per risk profile. No numeric
# constraints (the API's structured-output schema doesn't support them) — the
# horizon is capped to a week in the prompt and clamped in code.
_SUGGESTION_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "portfolio_note": {"type": "string"},
        "suggestions": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "ticker": {"type": "string"},
                    "action": {
                        "type": "string",
                        "enum": ["buy", "hold", "trim", "sell"],
                    },
                    "horizon_days": {"type": "integer"},
                    "headline": {"type": "string"},
                    "reasoning": {"type": "string"},
                    "price_trigger": {"type": "string"},
                    "risks": {"type": "string"},
                },
                "required": [
                    "ticker",
                    "action",
                    "horizon_days",
                    "headline",
                    "reasoning",
                    "price_trigger",
                    "risks",
                ],
            },
        },
    },
    "required": ["portfolio_note", "suggestions"],
}


class ClaudeClient:
    """Minimal Claude Messages API client over the standard library.

    One method — ``complete_json`` — asks Claude for a response constrained to a
    JSON schema (structured outputs) and returns the parsed object. Uses adaptive
    thinking so the model reasons before committing to an answer.
    """

    API_URL = "https://api.anthropic.com/v1/messages"
    ANTHROPIC_VERSION = "2023-06-01"

    def __init__(self, api_key: str = None, model: str = "claude-opus-4-8",
                 timeout: int = 180):
        self.api_key = api_key
        self.model = model
        self.timeout = timeout

    def available(self) -> bool:
        """True when an Anthropic API key is configured."""
        return bool(self.api_key)

    def complete_json(self, system: str, prompt: str, schema: dict,
                      max_tokens: int = 16000) -> dict:
        """Send one request and return the parsed JSON object Claude produced.

        Raises RuntimeError with a readable message on any API/parse failure so
        the service can surface it and keep the last good suggestions on screen.
        """
        if not self.api_key:
            raise RuntimeError("ANTHROPIC_API_KEY is not set.")

        body = json.dumps(
            {
                "model": self.model,
                "max_tokens": max_tokens,
                # Adaptive thinking: Claude decides how much to reason. Effort
                # medium keeps cost/latency sensible for a periodic job.
                "thinking": {"type": "adaptive"},
                "output_config": {
                    "effort": "medium",
                    "format": {"type": "json_schema", "schema": schema},
                },
                "system": system,
                "messages": [{"role": "user", "content": prompt}],
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            self.API_URL,
            data=body,
            method="POST",
            headers={
                "x-api-key": self.api_key,
                "anthropic-version": self.ANTHROPIC_VERSION,
                "content-type": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace"))
        except urllib.error.HTTPError as e:
            detail = self._error_detail(e)
            raise RuntimeError(f"Claude API error ({e.code}): {detail}")
        except urllib.error.URLError as e:
            raise RuntimeError(f"Could not reach the Claude API: {e.reason}")

        # With structured outputs the model returns valid JSON in a text block.
        # Adaptive thinking may prepend thinking blocks, so scan for the text.
        text = next(
            (b.get("text") for b in data.get("content", []) if b.get("type") == "text"),
            None,
        )
        if not text:
            raise RuntimeError("Claude returned no text content.")
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            raise RuntimeError("Claude returned malformed JSON.")

    @staticmethod
    def _error_detail(e: urllib.error.HTTPError) -> str:
        try:
            payload = json.loads(e.read().decode("utf-8", "replace"))
            return payload.get("error", {}).get("message", "unknown error")
        except Exception:
            return "unknown error"


class OllamaClient:
    """Local-model client (Ollama) with the same interface as ClaudeClient.

    Runs the model on your own machine — nothing leaves the laptop and no API key
    is needed. Talks to a local Ollama server (``ollama serve``) over the
    standard library, using its structured-output support (``format`` = a JSON
    schema) so the model returns JSON matching our suggestion shape.

    Swap this in for ClaudeClient and ``AIAdvisorService`` works unchanged.
    """

    def __init__(self, host: str = None, model: str = "llama3.1",
                 timeout: int = 300):
        self.host = (host or "http://localhost:11434").rstrip("/")
        self.model = model
        self.timeout = timeout

    def available(self) -> bool:
        """Local model is always 'configured' — reachability problems surface as
        clear errors at generation time instead."""
        return True

    def complete_json(self, system: str, prompt: str, schema: dict,
                      max_tokens: int = 16000) -> dict:
        """Send one chat request constrained to the JSON schema and return the
        parsed object. Raises RuntimeError with a readable message on failure."""
        body = json.dumps(
            {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": prompt},
                ],
                "stream": False,
                # Ollama structured outputs: pass the JSON schema directly.
                "format": schema,
                "options": {"num_predict": max_tokens, "temperature": 0.3},
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            self.host + "/api/chat",
            data=body,
            method="POST",
            headers={"content-type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace"))
        except urllib.error.HTTPError as e:
            detail = self._error_detail(e)
            # A missing model is the most common setup error — make it actionable.
            if "not found" in detail.lower() or e.code == 404:
                raise RuntimeError(
                    f"Ollama model '{self.model}' isn't installed. "
                    f"Run: ollama pull {self.model}"
                )
            raise RuntimeError(f"Ollama error ({e.code}): {detail}")
        except urllib.error.URLError as e:
            raise RuntimeError(
                f"Could not reach Ollama at {self.host} — is `ollama serve` "
                f"running? ({e.reason})"
            )

        content = (data.get("message") or {}).get("content")
        if not content:
            raise RuntimeError("Ollama returned no content.")
        try:
            return json.loads(content)
        except json.JSONDecodeError:
            raise RuntimeError("Ollama returned malformed JSON.")

    @staticmethod
    def _error_detail(e: urllib.error.HTTPError) -> str:
        try:
            payload = json.loads(e.read().decode("utf-8", "replace"))
            return payload.get("error", "unknown error")
        except Exception:
            return "unknown error"


def _extract_json(text: str) -> dict:
    """Parse a JSON object from model output, tolerating markdown fences or
    stray prose around it. Raises RuntimeError if nothing parseable is found."""
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    # Fall back to the outermost {...} span (handles ```json fences / preamble).
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            pass
    raise RuntimeError("Model returned malformed JSON.")


class LlamaClient:
    """Meta-internal Llama API client (MetaGen), same interface as the others.

    Uses the company-provided, OpenAI-compatible endpoint — free/self-serve for
    employees, callable from a local laptop on the corp network (VPN) with a
    Bearer key, and keeps inference on Meta-hosted models. Stdlib ``urllib`` only.

      POST {base}/compat/v1/chat/completions   (OpenAI Chat Completions shape)
      Authorization: Bearer LLM|<app-id>|<secret>

    Get a key at https://www.internalfb.com/metagen/tools/llm-api-keys and an
    entitlement at https://www.internalfb.com/metagen/tools/entitlements.
    """

    def __init__(self, api_key: str = None,
                 model: str = "llama4-scout-17b-16e-instruct",
                 base_url: str = "https://api.llama.com", timeout: int = 180):
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def available(self) -> bool:
        """True when a Llama API key is configured."""
        return bool(self.api_key)

    def complete_json(self, system: str, prompt: str, schema: dict,
                      max_tokens: int = 16000) -> dict:
        """Send one chat request and return the parsed JSON object.

        The compat endpoint may not enforce a JSON schema, so we ask for a JSON
        object, embed the schema in the instructions, and parse defensively.
        """
        if not self.api_key:
            raise RuntimeError("LLAMA_API_KEY is not set.")

        system_with_schema = (
            f"{system}\n\nReturn ONLY a single JSON object — no markdown, no "
            f"prose — that matches this JSON schema:\n{json.dumps(schema)}"
        )
        body = json.dumps(
            {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system_with_schema},
                    {"role": "user", "content": prompt},
                ],
                "stream": False,
                "max_completion_tokens": max_tokens,
                "temperature": 0.3,
                "response_format": {"type": "json_object"},
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            self.base_url + "/compat/v1/chat/completions",
            data=body,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace"))
        except urllib.error.HTTPError as e:
            detail = self._error_detail(e)
            low = detail.lower()
            if e.code == 403 and "corp" in low:
                raise RuntimeError(
                    "Llama API needs the corp network — connect to VPN and retry."
                )
            if (
                "does not have access" in low
                or "invalid model" in low
                or "not available" in low
            ):
                raise RuntimeError(
                    f"Llama model '{self.model}' isn't available to your key. "
                    "Grant model access on your MetaGen entitlement (its "
                    "'Available Models' tab), then set LLAMA_MODEL to a listed "
                    "name. Details: " + detail
                )
            raise RuntimeError(f"Llama API error ({e.code}): {detail}")
        except urllib.error.URLError as e:
            raise RuntimeError(
                f"Could not reach the Llama API at {self.base_url} "
                f"(on VPN?): {e.reason}"
            )

        try:
            content = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            raise RuntimeError("Llama API returned an unexpected response shape.")
        if not content:
            raise RuntimeError("Llama API returned no content.")
        return _extract_json(content)

    @staticmethod
    def _error_detail(e: urllib.error.HTTPError) -> str:
        try:
            payload = json.loads(e.read().decode("utf-8", "replace"))
            err = payload.get("error")
            if isinstance(err, dict):
                return err.get("message", "unknown error")
            return err or payload.get("message", "unknown error")
        except Exception:
            return "unknown error"


class GeminiClient:
    """Google Gemini API client — free, high rate limit, strong news grounding.

    Uses Google's native ``generateContent`` endpoint over stdlib ``urllib``
    (no SDK, matching the rest of the app), with ``responseMimeType:
    application/json`` to force structured JSON output. Falls back to an
    OpenAI-compatible endpoint when the base URL contains ``/openai``.

    Free tier (no credit card):
      - gemini-2.0-flash: 15 RPM / 1M TPM / 200 RPD  (recommended default)
      - gemini-2.5-flash-lite: 15 RPM / 250K TPM / 1000 RPD
      - gemini-2.0-flash-lite: 30 RPM / 1M TPM / 200 RPD
      - Context window 1M tokens, supports Google Search grounding.

      Get a key at https://aistudio.google.com/app/apikey

    Env:
      GEMINI_API_KEY  — required
      GEMINI_MODEL    — optional, default ``gemini-2.0-flash``
      GEMINI_API_BASE — optional, default
                       ``https://generativelanguage.googleapis.com/v1beta``

    For OpenAI-compatible mode, set::
      GEMINI_API_BASE=https://generativelanguage.googleapis.com/v1beta/openai
    """

    def __init__(self, api_key: str = None,
                 model: str = "gemini-flash-lite-latest",
                 base_url: str = "https://generativelanguage.googleapis.com/v1beta",
                 timeout: int = 180):
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout

    def available(self) -> bool:
        return bool(self.api_key)

    def complete_json(self, system: str, prompt: str, schema: dict,
                      max_tokens: int = 16000) -> dict:
        if not self.api_key:
            raise RuntimeError("GEMINI_API_KEY is not set.")

        system_with_schema = (
            f"{system}\n\nReturn ONLY a single JSON object — no markdown, no "
            f"prose — that matches this JSON schema:\n{json.dumps(schema)}"
        )

        # If user pointed at the OpenAI-compatible base, use that path.
        if "openai" in self.base_url.lower():
            return self._complete_openai_compat(system_with_schema, prompt,
                                                 schema, max_tokens)
        return self._complete_native(system_with_schema, prompt,
                                      schema, max_tokens)

    # --- native generateContent path (default, recommended) -------------

    def _complete_native(self, system_with_schema: str, prompt: str,
                         schema: dict, max_tokens: int) -> dict:
        # Gemini native endpoint uses key as query param (also accepts
        # x-goog-api-key header, but query param is simplest with urllib).
        url = (f"{self.base_url}/models/{self.model}:generateContent"
               f"?key={urllib.parse.quote(self.api_key)}")

        body = json.dumps(
            {
                "systemInstruction": {
                    "parts": [{"text": system_with_schema}]
                },
                "contents": [
                    {"role": "user", "parts": [{"text": prompt}]}
                ],
                "generationConfig": {
                    "temperature": 0.3,
                    "maxOutputTokens": max_tokens,
                    # Force JSON output; schema enforcement is optional but
                    # responseMimeType alone is enough + our defensive parse.
                    "responseMimeType": "application/json",
                    # Including responseSchema helps accuracy; Gemini accepts a
                    # simplified JSON schema. Strip additionalProperties which it
                    # may reject on some models.
                    "responseSchema": self._strip_additional_properties(schema),
                },
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            url,
            data=body,
            method="POST",
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace"))
        except urllib.error.HTTPError as e:
            detail = self._error_detail(e)
            low = detail.lower()
            if e.code == 429:
                raise RuntimeError(
                    f"Gemini API rate limited (429): {detail}. "
                    f"Free tier: 15 RPM / 200-1000 RPD depending on model. "
                    f"Try {self.model} or wait."
                )
            if e.code == 400 and "api key" in low:
                raise RuntimeError(f"Gemini API key invalid: {detail}")
            raise RuntimeError(f"Gemini API error ({e.code}): {detail}")
        except urllib.error.URLError as e:
            raise RuntimeError(
                f"Could not reach Gemini API at {self.base_url} ({e.reason})"
            )

        # Expected shape: {candidates: [{content: {parts: [{text: "..."}]}}]}
        try:
            candidates = data.get("candidates") or []
            content = candidates[0].get("content", {}) if candidates else {}
            parts = content.get("parts") or []
            text = parts[0].get("text") if parts else None
        except (KeyError, IndexError, TypeError):
            text = None

        if not text:
            # Include full payload in error for debugging (truncated)
            preview = json.dumps(data)[:500]
            raise RuntimeError(
                f"Gemini API returned no text content: {preview}"
            )
        return _extract_json(text)

    # --- OpenAI-compatible path (optional) --------------------------------

    def _complete_openai_compat(self, system_with_schema: str, prompt: str,
                                schema: dict, max_tokens: int) -> dict:
        url = self.base_url + "/chat/completions"
        body = json.dumps(
            {
                "model": self.model,
                "messages": [
                    {"role": "system", "content": system_with_schema},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "max_tokens": max_tokens,
                "max_completion_tokens": max_tokens,
                "response_format": {"type": "json_object"},
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            url,
            data=body,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = json.loads(resp.read().decode("utf-8", "replace"))
        except urllib.error.HTTPError as e:
            detail = self._error_detail(e)
            if e.code == 429:
                raise RuntimeError(f"Gemini API rate limited (429): {detail}")
            raise RuntimeError(f"Gemini API error ({e.code}): {detail}")
        except urllib.error.URLError as e:
            raise RuntimeError(
                f"Could not reach Gemini API at {self.base_url} ({e.reason})"
            )

        try:
            content = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            raise RuntimeError("Gemini API returned an unexpected response shape.")
        if not content:
            raise RuntimeError("Gemini API returned no content.")
        return _extract_json(content)

    @staticmethod
    def _strip_additional_properties(schema: dict) -> dict:
        """Remove ``additionalProperties`` keys which some Gemini models reject.
        Deep copies only the levels we care about, to stay minimal."""
        def _strip(obj):
            if isinstance(obj, dict):
                out = {}
                for k, v in obj.items():
                    if k == "additionalProperties":
                        continue
                    out[k] = _strip(v)
                return out
            if isinstance(obj, list):
                return [_strip(x) for x in obj]
            return obj
        try:
            return _strip(schema)
        except Exception:
            # If stripping fails, return original — API may still accept.
            return schema

    @staticmethod
    def _error_detail(e: urllib.error.HTTPError) -> str:
        try:
            raw = e.read().decode("utf-8", "replace")
            payload = json.loads(raw)
            # Gemini error shape: {"error": {"message": "...", "code": ...}}
            err = payload.get("error")
            if isinstance(err, dict):
                return err.get("message", raw[:500])
            if isinstance(err, str):
                return err
            return payload.get("message", raw[:500])
        except Exception:
            try:
                return e.read().decode("utf-8", "replace")[:500]
            except Exception:
                return "unknown error"


# --- Advisor service ----------------------------------------------------

# The two risk profiles the advisor always produces, so the UI toggle is instant
# (no new API call on toggle — both are generated each refresh).
_RISK_PROFILES = ("low", "high")

# Suggestions look at most one week ahead, per the product spec.
_MAX_HORIZON_DAYS = 7

_SYSTEM_PROMPT = (
    "You are a sharp, concise equity analyst helping a retail investor manage a "
    "small personal stock portfolio. You are given the investor's holdings (with "
    "average cost and cost basis), live prices and today's move, the full history "
    "of unrealized gains across 1D/1W/1M/YTD/1Y/Total windows, realized gains, "
    "and recent news headlines per ticker.\n\n"
    "For EACH holding, decide whether to buy more, hold, trim (sell part), or "
    "sell (the entire position). Your view is short-term: the horizon must be "
    "between 1 and 7 days — never longer than a week. Combine both risk and "
    "expected gain, and tailor everything to the requested risk tolerance.\n\n"
    "Be specific and actionable. When relevant, give a concrete price trigger "
    "for the week (e.g. 'if it drops below $320 this week, sell before it does'). "
    "Ground your reasoning in the data and news provided — cite momentum, the "
    "cost basis, upcoming earnings, and specific headlines. Keep each detailed "
    "reasoning to roughly 8-12 short lines. Keep the summary headline to one "
    "short line. Do not give generic disclaimers; be direct."
)


class AIAdvisorService:
    """Generates, caches, and refreshes the AI suggestions.

    Composes Claude with the market/portfolio/summary services and the news
    provider. Produces both a low-risk and a high-risk set every refresh and
    caches them together, so the UI's risk toggle never triggers a new API call.
    Persists the latest result so a restart shows the last suggestions.
    """

    def __init__(self, claude: ClaudeClient, news, market, portfolio, summary,
                 storage=None, refresh_hours: int = 2):
        self.claude = claude
        self.news = news
        self.market = market
        self.portfolio = portfolio
        self.summary = summary
        self.storage = storage
        self.refresh_seconds = refresh_hours * 3600

        self._lock = threading.Lock()
        self._refreshing = False
        self._latest = self._load_persisted()

    # --- public API -----------------------------------------------------

    def get(self) -> dict:
        """Return the latest cached suggestions plus status for the UI."""
        latest = self._latest
        return {
            "configured": self.claude.available(),
            "news_configured": self.news.available(),
            "refreshing": self._refreshing,
            "market_open": is_market_open(),
            "refresh_hours": self.refresh_seconds // 3600,
            "generated_at": latest.get("generated_at") if latest else None,
            "risk_profiles": latest.get("risk_profiles") if latest else None,
            "error": latest.get("error") if latest else None,
        }

    def request_refresh(self) -> bool:
        """Kick off a background regeneration. Returns False if one is running
        or the advisor isn't configured (nothing to do)."""
        if not self.claude.available() or self._refreshing:
            return False
        threading.Thread(target=self._safe_generate, daemon=True).start()
        return True

    def start_scheduler(self):
        """Start the background loop: generate once on boot (if nothing is
        cached), then refresh every ``refresh_hours`` during market hours."""
        if not self.claude.available():
            print("AI advisor: no model configured — advisor disabled.")
            return
        threading.Thread(target=self._scheduler_loop, daemon=True).start()

    # --- scheduler ------------------------------------------------------

    def _scheduler_loop(self):
        # Generate immediately on boot if we have nothing to show yet.
        if self._latest is None:
            self._safe_generate()
        while True:
            time.sleep(300)  # re-check every 5 minutes
            if not is_market_open():
                continue
            last = self._generated_at_epoch()
            if last is None or (time.time() - last) >= self.refresh_seconds:
                self._safe_generate()

    def _safe_generate(self):
        """Run one generation, guarded so only one runs at a time. Never raises."""
        with self._lock:
            if self._refreshing:
                return
            self._refreshing = True
        try:
            self._generate()
        except Exception as e:  # keep the last good result on screen
            print(f"AI advisor: generation failed: {e}")
            if self._latest is None:
                self._latest = {
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "risk_profiles": None,
                    "error": str(e),
                }
        finally:
            self._refreshing = False

    # --- generation -----------------------------------------------------

    def _generate(self):
        context = self._gather_context()
        profiles = {}
        error = None
        for risk in _RISK_PROFILES:
            prompt = self._build_prompt(context, risk)
            result = self.claude.complete_json(
                _SYSTEM_PROMPT, prompt, _SUGGESTION_SCHEMA
            )
            profiles[risk] = self._clean_profile(result)

        self._latest = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "risk_profiles": profiles,
            "error": error,
        }
        self._persist(self._latest)
        print(f"AI advisor: suggestions refreshed at {self._latest['generated_at']}.")

    def _gather_context(self) -> dict:
        """Assemble everything the model needs from the existing services."""
        holdings = self.market.holdings_view()
        summary = self.summary.summary()

        # Compact the unrealized history to headline value + pct per window (the
        # graph series themselves are too large and not needed for reasoning).
        unrealized = {
            key: {"value": v.get("value"), "pct": v.get("pct")}
            for key, v in (summary.get("unrealized") or {}).items()
        }

        tickers = [h["ticker"] for h in holdings]
        news = self.news.get_news_many(tickers)

        return {
            "as_of": datetime.now(timezone.utc).isoformat(),
            "total_worth": summary.get("total_worth"),
            "realized_gains": summary.get("realized"),
            "unrealized_gains_history": unrealized,
            "holdings": [
                {
                    "ticker": h["ticker"],
                    "shares": h["shares"],
                    "avg_price": h["avg_price"],
                    "cost_basis": h["cost_basis"],
                    "price": h["price"],
                    "previous_close": h["previous_close"],
                    "market_value": h["market_value"],
                    "today_move": h["today"],
                    "total_unrealized": h["total"],
                    "earnings_date": h["earnings_date"],
                    "recent_news": news.get(h["ticker"], []),
                }
                for h in holdings
            ],
        }

    def _build_prompt(self, context: dict, risk: str) -> str:
        if risk == "low":
            stance = (
                "The investor wants a LOW-RISK stance: prioritise capital "
                "preservation and steady gains over aggressive upside. Prefer "
                "holding or trimming into strength, be quick to protect against "
                "downside, and only suggest buying more when the risk/reward is "
                "clearly favourable."
            )
        else:
            stance = (
                "The investor wants a HIGH-RISK stance: prioritise maximising "
                "gains and is comfortable with volatility. Be willing to buy the "
                "dip and add to conviction positions, and only trim or sell when "
                "there's a strong short-term reason."
            )
        return (
            f"{stance}\n\n"
            "Here is the current portfolio and market context as JSON. All "
            "monetary values are in the position's currency; gains are shown as "
            "{value, pct}. 'unrealized_gains_history' shows the accrued gain over "
            "each window so you can read momentum.\n\n"
            f"{json.dumps(context, indent=2, default=str)}\n\n"
            "Return one suggestion per holding. horizon_days must be 1-7. "
            "'action' is one of buy (buy more), hold, trim (sell part), sell "
            "(sell the whole position). 'headline' is the one-line summary; "
            "'reasoning' is the ~10-line explanation; 'price_trigger' is a "
            "concrete price-based action for the week (empty string if none); "
            "'risks' names the main risk to this call."
        )

    @staticmethod
    def _clean_profile(result: dict) -> dict:
        """Clamp horizons to the 1-7 day window and normalise shapes."""
        suggestions = []
        for s in result.get("suggestions", []) or []:
            horizon = s.get("horizon_days") or 1
            try:
                horizon = max(1, min(_MAX_HORIZON_DAYS, int(horizon)))
            except (TypeError, ValueError):
                horizon = _MAX_HORIZON_DAYS
            suggestions.append(
                {
                    "ticker": (s.get("ticker") or "").upper(),
                    "action": s.get("action") or "hold",
                    "horizon_days": horizon,
                    "headline": s.get("headline") or "",
                    "reasoning": s.get("reasoning") or "",
                    "price_trigger": s.get("price_trigger") or "",
                    "risks": s.get("risks") or "",
                }
            )
        return {
            "portfolio_note": result.get("portfolio_note") or "",
            "suggestions": suggestions,
        }

    # --- persistence ----------------------------------------------------

    def _load_persisted(self):
        if self.storage is None:
            return None
        try:
            data = self.storage.load()
            return data.get("latest")
        except Exception:
            return None

    def _persist(self, latest: dict):
        if self.storage is None:
            return
        try:
            self.storage.save({"latest": latest})
        except Exception as e:
            print(f"AI advisor: could not persist suggestions: {e}")

    def _generated_at_epoch(self):
        if not self._latest or not self._latest.get("generated_at"):
            return None
        try:
            return datetime.fromisoformat(self._latest["generated_at"]).timestamp()
        except (TypeError, ValueError):
            return None
